### ISSUE TITLE
error running in windows

### ISSUE THREAD

**Issue by prabirshrestha** [roxma/vim-hug-neovim-rpc#2]
if !has('nvim')
      " pip install msgpack-python
      Plug 'roxma/vim-hug-neovim-rpc'
    endif
    Plug 'roxma/nvim-completion-manager'

![image](https://cloud.githubusercontent.com/assets/287744/23135626/321c7478-f74e-11e6-9ac1-322b40d9b2f2.png)

**Comment by roxma** [comment]
This plugin explicitly use `python2` and `python3` command, Copy the installed python into corresponding python2 and python3  and setup the `PATH` environment would fix this issue

However, I still have troubles connecting the python channel.

Python on Windows is really a big pain.

**Comment by roxma** [comment]
This is the error I run into currently.

```
2017-02-21 11:57:51,962 [ERROR @ base_events.py:default_exception_handler:1259] 75180 - Fatal read error on pipe transport
protocol: <neovim.msgpack_rpc.event_loop.asyncio.AsyncioEventLoop object at 0x02C5EF30>
transport: <_ProactorReadPipeTransport fd=0>
Traceback (most recent call last):
  File "C:\Users\roxma\AppData\Local\Programs\Python\Python36-32\lib\asyncio\proactor_events.py", line 202, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 4096)
  File "C:\Users\roxma\AppData\Local\Programs\Python\Python36-32\lib\asyncio\windows_events.py", line 430, in recv
    self._register_with_iocp(conn)
  File "C:\Users\roxma\AppData\Local\Programs\Python\Python36-32\lib\asyncio\windows_events.py", line 611, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 6] 句柄无效。
2017-02-21 11:57:51,964 [ERROR @ cm_start.py:main:85] 75180 - Exception when running cm_core: [WinError 6] 句柄无效。
Traceback (most recent call last):
  File "D:\work\git\plugged\nvim-completion-manager\pythonx\cm_start.py", line 60, in main
    nvim = nvim_env()
  File "D:\work\git\plugged\nvim-completion-manager\pythonx\cm_start.py", line 92, in nvim_env
    nvim = attach('stdio')
  File "C:\Users\roxma\AppData\Local\Programs\Python\Python36-32\lib\site-packages\neovim\__init__.py", line 102, in attach
    stdio_session() if session_type == 'stdio' else
  File "C:\Users\roxma\AppData\Local\Programs\Python\Python36-32\lib\site-packages\neovim\msgpack_rpc\__init__.py", line 37, in stdio_session
    return session('stdio')
  File "C:\Users\roxma\AppData\Local\Programs\Python\Python36-32\lib\site-packages\neovim\msgpack_rpc\__init__.py", line 18, in session
    loop = EventLoop(transport_type, *args, **kwargs)
  File "C:\Users\roxma\AppData\Local\Programs\Python\Python36-32\lib\site-packages\neovim\msgpack_rpc\event_loop\base.py", line 88, in __init__
    getattr(self, '_connect_{}'.format(transport_type))(*args)
  File "C:\Users\roxma\AppData\Local\Programs\Python\Python36-32\lib\site-packages\neovim\msgpack_rpc\event_loop\asyncio.py", line 93, in _connect_stdio
    self._loop.run_until_complete(coroutine)
  File "C:\Users\roxma\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "C:\Users\roxma\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 1114, in connect_write_pipe
    transport = self._make_write_pipe_transport(pipe, protocol, waiter)
  File "C:\Users\roxma\AppData\Local\Programs\Python\Python36-32\lib\asyncio\proactor_events.py", line 423, in _make_write_pipe_transport
    sock, protocol, waiter, extra)
  File "C:\Users\roxma\AppData\Local\Programs\Python\Python36-32\lib\asyncio\proactor_events.py", line 316, in __init__
    self._read_fut = self._loop._proactor.recv(self._sock, 16)
  File "C:\Users\roxma\AppData\Local\Programs\Python\Python36-32\lib\asyncio\windows_events.py", line 430, in recv
    self._register_with_iocp(conn)
  File "C:\Users\roxma\AppData\Local\Programs\Python\Python36-32\lib\asyncio\windows_events.py", line 611, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 6] 句柄无效。
```

**Comment by roxma** [comment]
Previous error is fix by [this commit](https://github.com/roxma/nvim-completion-manager/commit/bd8efd297324282c72fb811329ea327153ccd459)

I got another issue, the vim process is freezed.

**Comment by roxma** [comment]
@prabirshrestha  

I've pushed some changes. It's working on my Windows now.

Make sure `python2` and `python3` can be found in your `PATH`

![animation](https://cloud.githubusercontent.com/assets/4538941/23158429/25adf8c6-f85a-11e6-9e46-3c6e2b629453.gif)

**Comment by prabirshrestha** [comment]
@roxma still doesn't work for me in vim8 on windows. I think it is because I have `  set shellslash` enabled.

Notice the forward slash before pythonx in `C:\Users\prshrest\.config\nvim\cache\plugins\vim-hug-neovim-rpc/pythonx\neovim_rpc_server.py`. It says cannot find the file specified.

![image](https://cloud.githubusercontent.com/assets/287744/23186498/3ba783e0-f83c-11e6-9bd1-7f2790bb4ef7.png)

**Comment by markonm** [comment]
I still get this error even after I updated plugins.

```
Error detected while processing function cm#enable_for_buffer[40]..<SNR>34_start_core_channel[5]..neovim_rpc#jobstart:
line   11:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Marko\vimfiles\plugged\vim-hug-neovim-rpc\pythonx\neovim_rpc_server.py", line 466, in jobstart
    proc = subprocess.Popen(args=vim.vars['_neovim_rpc_tmp_args'][0], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=DEVNULL, startupinfo=startupinfo)
  File "C:\Users\Marko\AppData\Local\Programs\Python\Python35-32\Lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Marko\AppData\Local\Programs\Python\Python35-32\Lib\subprocess.py", line 929, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\Marko\AppData\Local\Programs\Python\Python35-32\Lib\subprocess.py", line 441, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'
line   12:
E121: Undefined variable: g:_neovim_rpc_tmp_ret
E15: Invalid expression: g:_neovim_rpc_tmp_ret>0
line   17:
E121: Undefined variable: g:_neovim_rpc_tmp_ret
E15: Invalid expression: g:_neovim_rpc_tmp_ret
```
I use vim8 with python3 on Windows 10. Python3 is in my path. On WSL with vim8 I don't get an error but I can't get completions either.

Could you elaborate this part of your instructions?
>    Copy the installed python into corresponding python2 and python3

**Comment by prabirshrestha** [comment]
Now I do get the same error as @xtal8 .ie. `TypeError: a bytes-like object is required, not 'str'`

Not an expert in python but after googling around it seems that it can be fixed by converting the binary to utf-8 string.

`print(vim.vars['_neovim_rpc_tmp_args'][0][0])` seems to print `b'python3`.

The fix would be

```python
args = map(lambda x: x.decode('utf-8'), vim.vars['_neovim_rpc_tmp_args'][0])
proc = subprocess.Popen(args=args, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=DEVNULL, startupinfo=startupinfo)
```

I made a copy of `python.exe` as `python3.exe` which is in the path and when I open vim I do see an instance of python3.exe in task manager. But when I type I don't see any autocomplete suggestions.

Also doesn't seem like a bug with shellslash. I tried with this minimal vimrc with both forward and black slashes and I get the same error.

```viml
set runtimepath+=~/.vim-plugins/vim-hug-neovim-rpc
set runtimepath+=~/.vim-plugins/nvim-completion-manager
```

I'm using `Python 3.6.0`. I have python2.7 installed too

**Comment by roxma** [comment]
@prabirshrestha 
Thanks. I've only tested this plugin on vim8 with `has('python')`, I'll find some time to test it with `has('python3')`

**Comment by roxma** [comment]
I've pushed some changes, It works on my windows with `has('python3')` now.

**Comment by prabirshrestha** [comment]
hmm. Works on neovim on windows but not on vim8. I no longer see any errors in vim8.

@roxma do you have a minimal vimrc that I could try.

 I have both `has('python')` and `has('python3')`.

**Comment by roxma** [comment]
Set these two environment variable to write log files to current working directory.  And check if there's any useful information.

```
NVIM_PYTHON_LOG_FILE=nvim.log 
NVIM_PYTHON_LOG_LEVEL=INFO
```

My minimal vimrc (requires vim-plug):

```vim

call plug#begin('~/.vim/plugged')


" `npm install` For javascript code completion support
Plug 'roxma/nvim-completion-manager'

if !has('nvim')
    Plug 'roxma/vim-hug-neovim-rpc'
endif

call plug#end()

```


![animation](https://cloud.githubusercontent.com/assets/4538941/23254604/8fc29fba-f9f3-11e6-81f3-35eb12bca947.gif)

**Comment by prabirshrestha** [comment]
Still didn't work. 
Here is the log from 'nvim.log_py3_neovim_rpc_server`.
I open vim and let it stay: http://pastebin.com/ZQhs6dNb
I open vim and exit: http://pastebin.com/uugz8ZfJ

I'm using x64 bit version of vim from https://tuxproject.de/projects/vim/ Which vim distribution are you using?

I copied python.exe and made a duplicate at `C:\Users\prshrest\AppData\Local\Programs\Python\Python36\python3.exe`. I do have python 2 installed too.

`nvim.log_py3_cm_core` has no logs at all.

**Comment by roxma** [comment]
I'm using 32 bit version downloaded from vim.org, with python 3.5.3 (vim8 says required 3.5 when I type `:python3 print('hi')` )
The python should also be 32 bit as the gvim version.

It seems I run into the same issue before, where nvim.log_py3_cm_core has no logs at all.

Also should update both plugins to the latest version.

**Comment by prabirshrestha** [comment]
Updated the plugins to the latest version and finally works even in vim tux 64 bit build with python 3.6.

@roxma thanks for all the help.
